### ISSUE TITLE
Vista: registro usuario

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-userapp#12]
en general todos los datos de una tienda, menos su imagen.
![image](https://user-images.githubusercontent.com/69495972/98327265-2bdd3a80-1fc1-11eb-8258-f9b14cd92f94.png)

**Comment by Jeronimo90-eng** [comment]
<img width="356" alt="Captura de Pantalla 2020-11-15 a la(s) 12 52 32 a  m" src="https://user-images.githubusercontent.com/69558043/99178117-0695ae00-26de-11eb-97de-e7c95094773b.png">
