### ISSUE TITLE
Vista: home tienda

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-userapp#14]
debe agrupar los productos por categoria y cuando elija una categoria solo mostrar los de esa categoria, mostrar los iconos de las categorias

en el header monstrar el nombre de la tienda

![image](https://user-images.githubusercontent.com/69495972/98327582-de150200-1fc1-11eb-9dbb-2f219578b819.png)

cuando se presione un producto se debe ir aqui:
![image](https://user-images.githubusercontent.com/69495972/98327867-888d2500-1fc2-11eb-8cce-c7ea2c4ffee4.png)

para agregarlo al carrito

antes agregue manualmente aca las imagenes de las categorias cyo nombre sera el codigo de la categria.jpg
https://github.com/eamquindio/mitiendacdn/tree/main/categories

**Comment by ErrorHyperion** [comment]
![image](https://user-images.githubusercontent.com/69517323/99178480-7eb1a300-26e1-11eb-8a53-546cacfb35f6.png)
![image](https://user-images.githubusercontent.com/69517323/99178485-8b35fb80-26e1-11eb-968a-3d3628f7b20a.png)
![image](https://user-images.githubusercontent.com/69517323/99178497-a1dc5280-26e1-11eb-9ffd-1dd089900fe9.png)
