### ISSUE TITLE
Vista: ver el shopping cart

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-userapp#15]
mostrar en el header el total de productos del shopping cart y el precio total.

![image](https://user-images.githubusercontent.com/69495972/98327949-b2464c00-1fc2-11eb-8aeb-3bb49bed96c0.png)

el boton buy-now crea la orden, despues de eso volver a la pantalla del historial de ordenes

**Comment by INGJOSEHV** [comment]
![image](https://user-images.githubusercontent.com/69516521/99161627-4189e880-26c2-11eb-8a8d-5512bdebfcc5.png)
