### ISSUE TITLE
Vista: historial de ordenes

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-userapp#16]
Mostrar las ordenes ordenadas por estado, primero las activas, luego las finalizadas. las canceladas no

el icono de la orden es el icono de la tienda donde se compro, cuando se seleccione alguna orden se debe llamar la pantalla del detalle de la orden mandandole por parametro el id de la orden.

![image](https://user-images.githubusercontent.com/69495972/98328221-33054800-1fc3-11eb-964f-1102a7a57259.png)

el nombre es el nombre de la tienda donde compro
mostrar en la tarjeta el total de producto y el total de la orden y la fecha de compra.

**Comment by CristhianCAM** [comment]
![image](https://user-images.githubusercontent.com/69518355/99210613-43bc7780-2794-11eb-8f75-4cbae1d99b25.png)
